Testing well: Normal arguments
This time, you will test row_to_list() with normal arguments i.e. arguments mapping to the tuple (1, 0). The plot is provided to you for reference.
Remembering that the best practice is to test for two to three normal arguments, you will write two tests in this exercise.


How many normal arguments is it recommended to test?
One.
None.

#YES - At least two or three.







Assign the variable expected to the expected return value for the normal argument "123\t4,567\n".
import pytest
from preprocessing_helpers import row_to_list

def test_on_normal_argument_1():
    actual = row_to_list("123\t4,567\n")
    # Fill in with the expected return value for the argument "123\t4,567\n"
    expected = ["123", "4,567"]
    assert actual == expected, "Expected: {0}, Actual: {1}".format(expected, actual)
    
    
    


Complete the correct assert statement for test_on_normal_argument_2(), making sure to format the failure message appropriately.
import pytest
from preprocessing_helpers import row_to_list

def test_on_normal_argument_1():
    actual = row_to_list("123\t4,567\n")
    # Fill in with the expected return value for the argument "123\t4,567\n"
    expected = ["123", "4,567"]
    assert actual == expected, "Expected: {0}, Actual: {1}".format(expected, actual)
    
    
def test_on_normal_argument_2():
    actual = row_to_list("1,059\t186,606\n")
    expected = ["1,059", "186,606"]
    # Write the assert statement along with a failure message
    assert actual == expected, "Expected: {0}, Actual: {1}".format(expected, actual)








The tests for boundary values, values triggering special behavior and normal arguments have been written to a test module test_row_to_list.py. Run the tests in the IPython shell. Which bugs does the function have?

In [1]: !pytest test_row_to_list.py
============================== test session starts ==============================
platform linux -- Python 3.6.7, pytest-5.2.2, py-1.8.1, pluggy-0.12.0
Matplotlib: 3.1.1
Freetype: 2.6.1
rootdir: /tmp/tmp9w99n3eg
plugins: mock-1.11.2, mpl-0.10
collecting ... 
collected 7 items                                                               

test_row_to_list.py .......                                               [100%]

=============================== 7 passed in 0.32s ===============================




The function returns ["", "4,567"] for the boundary value "\t4,567\n" instead of None.
The function raises a SyntaxError for the special value "\n" instead of returning None.
The function returns None for the normal argument "123\t4,567\n" instead of returning a list.

#YES - The function does not have any bugs.
Well done! You tested the function row_to_list() on boundary values, values triggering special behavior and normal arguments. All the tests are passing. So you can be quite confident that the function is correctly coded! Note that this function does not have bad arguments, so you did not write any tests for that. Also note how mapping the arguments to tuples enabled us to categorize the arguments easily. Use this trick for other functions whenever applicable ;-)

